# Example command:
# 
#   ROS_DISTRO=humble-source docker-compose run gpu

x-base-cpu: &base-cpu
  privileged: true
  network_mode: host
  environment:
    QT_X11_NO_MITSHM: 1
  volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
    - ~/.Xauthority:/root/.Xauthority
  command: /bin/bash

x-base-gpu: &base-gpu
  <<: *base-cpu
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
  environment:
    NVIDIA_VISIBLE_DEVICES: all
    NVIDIA_DRIVER_CAPABILITIES: all

services:
  gpu:
    <<: *base-gpu
    image: moveit/moveit2:humble-source
    volumes:
      - ./ar3_moveit2:/root/ws_moveit/src/ar3_moveit2
      - ~/.Xauthority:/root/.Xauthority
    environment:
      DISPLAY: $DISPLAY

